version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/vendor"
    schedule:
      interval: "monthly"
    target-branch: "develop"

  - package-ecosystem: "npm"
    directory: "/fonts"
    schedule:
      interval: "monthly"
    target-branch: "develop"
