# This workflow runs the automated test and uploads the coverage results to codecov.io

name: "Run Codecov Tests"

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          Xvfb :99 -screen 0 1024x768x16 &
          export DISPLAY=:99
          npm install
          npm run test:coverage
          bash <(curl -s https://codecov.io/bash)
