name: Danger CI

on:
  pull_request:
    branches: [master, develop]

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Danger JS Action
        uses: danger/danger-js@9.1.8
        env:
          DANGER_DISABLE_TRANSPILATION: true
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
